name: CI/CD with GitHub Actions and AWS CodeDeploy

on:
  push:
    branches:
      - dev # dev 브랜치에 푸시될 때마다 워크플로우 실행

env:
  AWS_REGION: ap-northeast-2 # 당신의 AWS 리전으로 변경 (예: us-east-1, ap-northeast-2)
  S3_BUCKET_NAME: mydeploy-uplus # 당신의 S3 버킷 이름으로 변경 (수정된 이름 반영)
  CODE_DEPLOY_APPLICATION_NAME: MyWebApp # 당신의 CodeDeploy 애플리케이션 이름으로 변경
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: MyWebApp-Dev # 당신의 CodeDeploy 배포 그룹 이름으로 변경

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

  package:
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create deployment package
        run: zip -r deploy-package.zip . -x ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy-package.zip

  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Upload to S3
        run: aws s3 cp deploy-package.zip s3://${{ env.S3_BUCKET_NAME }}/dev/deploy-package.zip

      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ env.S3_BUCKET_NAME }},key=dev/deploy-package.zip,bundleType=zip \
            --description "Deployment from GitHub Actions Dev"